<!--
@component UNoticeBar
@lang zh-CN 提供 caller-controlled、非滚动的横幅反馈面；调用方拥有可见性、文字、tone 与关闭决定，组件不轮播、计时、自动消失或管理全局队列。
@lang en Provides a caller-controlled, non-scrolling banner-feedback surface; the caller owns visibility, text, tone, and close decision, while the component does not rotate, time, auto-dismiss, or manage a global queue.
-->
<template>
  <!-- @lang zh-CN 受控模板呈现说明如下。
  @lang en Controlled template-presentation explanation follows.
  <lang><zh-CN>只有 visible 与非空 text 同时成立才输出横幅，避免无文字符号被误解为完整提醒。</zh-CN><en>The banner outputs only when visible and non-empty text both hold, avoiding a textless symbol being mistaken for a complete notice.</en></lang> -->
  <view v-if="isVisible" :class="noticeClasses" role="status" aria-live="polite"><text class="u-notice-bar__marker" aria-hidden="true">!</text><text class="u-notice-bar__text">{{ text }}</text><button v-if="hasClose" class="u-notice-bar__close" type="button" @click="emitClose"><text>{{ closeText }}</text></button></view>
</template>

<script setup>
import { computed } from 'vue';

// <lang><zh-CN>稳定名称与现有 inline `u-notice` 并存；两者不 alias，避免误称 API 兼容。</zh-CN><en>The stable name coexists with existing inline `u-notice`; the two are not aliases, avoiding a false API-compatibility claim.</en></lang>
defineOptions({ name: 'u-notice-bar' });

// <lang><zh-CN>有限 tone 只选择视觉 token，不将应用消息解释为任何业务或后端结果。</zh-CN><en>Finite tones select visual tokens only and do not interpret application messages as business or backend results.</en></lang>
const supportedTones = Object.freeze(['info', 'success', 'warning', 'error']);

// <lang><zh-CN>调用方拥有 visible/text/tone/closeText；空 closeText 不生成默认本地化 close control。</zh-CN><en>The caller owns visible/text/tone/closeText; empty closeText generates no default localized close control.</en></lang>
const props = defineProps({ visible: { type: Boolean, default: false }, text: { type: String, default: '' }, tone: { type: String, default: 'info' }, closeText: { type: String, default: '' } });

// <lang><zh-CN>close 只是本地 intent；应用决定横幅是否消失、替换或保留。</zh-CN><en>Close is local intent only; the application decides whether the banner disappears, is replaced, or is retained.</en></lang>
const emit = defineEmits(['close']);

// <lang><zh-CN>未知 tone 回退 info，保持 class 和主题 token 表面有限。</zh-CN><en>An unknown tone falls back to info, keeping class and theme-token surface finite.</en></lang>
const safeTone = computed(() => supportedTones.includes(props.tone) ? props.tone : 'info');

// <lang><zh-CN>可见性要求 caller visible 和可读文字；文本不由组件默认生成。</zh-CN><en>Visibility requires caller-visible state and readable text; text is not default-generated by the component.</en></lang>
const isVisible = computed(() => props.visible && props.text.trim().length > 0);

// <lang><zh-CN>根 class 只含固定命名空间及已规范化 tone。</zh-CN><en>Root classes contain only the fixed namespace and normalized tone.</en></lang>
const noticeClasses = computed(() => ['u-notice-bar', `u-notice-bar--${safeTone.value}`]);

// <lang><zh-CN>close control 资格只由 caller 文字决定；组件不从 tone 推断关闭行为。</zh-CN><en>Close-control eligibility derives only from caller text; the component infers no close behavior from tone.</en></lang>
const hasClose = computed(() => props.closeText.trim().length > 0);

/**
 * @lang zh-CN 转发有文字 close control 的 intent；不写回 visible 或启动自动消失计时器。
 * @lang en Forwards intent from a labeled close control; it writes no visible state and starts no auto-dismiss timer.
 * @param {unknown} event <lang><zh-CN>原始平台点击事件。</zh-CN><en>Original platform click event.</en></lang>
 * @returns {void} <lang><zh-CN>无返回值；符合 guard 时 emit `close`。</zh-CN><en>No return value; emits `close` when the guard passes.</en></lang>
 */
function emitClose(event) {
  // <lang><zh-CN>guard 保护隐藏横幅和无标签 control，保持直接 handler 调用零副作用。</zh-CN><en>The guard protects hidden banners and label-less controls, keeping direct handler calls side-effect free.</en></lang>
  if (!isVisible.value || !hasClose.value) return;

  // <lang><zh-CN>事件交给调用方；组件不管理反馈队列或时间。</zh-CN><en>Hand the event to the caller; the component manages neither feedback queue nor time.</en></lang>
  emit('close', event);
}
</script>

<style src="./u-notice-bar.css"></style>
